github.com:
    users:
        Raza82:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Raza82
